### ISSUE TITLE
There is no release error

### ISSUE THREAD

**Issue by AlexShapka** [docksal/boilerplate-backdrop#10]
Downloading any contrib module with `drush dl module-name` gives: `There is no release error`.

For example, `drush dl devel` gives:

`Error: There is no release located at https://github.com/backdrop-contrib/devel/releases/download//devel.zip`

because the zip file is actually located at `https://github.com/backdrop-contrib/devel/archive/1.x-1.x.zip` instead.

**Comment by shelane** [comment]
I can repeat this error if I run `fin drush dl devel` from inside the `docroot` directory. However, if I'm at the root of the project and run `fin drush dl devel`, then I get:
```
Project devel (8.x-2.1) downloaded to /var/www/devel.                                                                                                                  [success]
Project devel contains 4 modules: kint, devel_generate, webprofiler, devel.
```

@AlexShapka Can you confirm?

**Comment by alanmels** [comment]
@shelane, this basically the same issue as https://github.com/backdrop-contrib/drush/issues/200 and can be closed as me and @AlexShapka use the same networks, so the problem was about bad connection. sorry for wrong alert.

**Comment by alanmels** [comment]
On the other hand, please read my last finding on https://github.com/backdrop-contrib/drush/issues/200#issuecomment-543331584

**Comment by shelane** [comment]
Since it was stated in that comment that it worked fine with the dev version as of this date, then I will close this. Docksal is using a newer version than that dev.
