### ISSUE TITLE
Error message connection to MySQL

### ISSUE THREAD

**Issue by shelane** [docksal/boilerplate-backdrop#4]
Running `fin init` on this project gives this error:
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
	Installing Backdrop. This may take a moment...
```

It does still install and run. However, the reports show this message:
```
Database tables need conversion less
4-byte UTF-8 support enables extended characters to be saved into the database, including emojis, Asian symbols and mathematical symbols. Your server supports this feature but not all tables have been converted to use it. After making a database backup, you should convert existing tables.
```

**Comment by klonos** [comment]
The first is a known issue: https://github.com/backdrop-contrib/drush/issues/195 ...it will eventually be solved upstream, so if you make sure that you are pulling the latest from https://github.com/backdrop-contrib/drush it should be fine.

The second error may have with the support for UTF-8 that has been added. If the underlaying db setup allows this, it will be enabled by default. This may have to do with using an outdated version of Backdrop, and may be solved by #7.

**Comment by Wylbur** [comment]
This boilerplate no longer uses drush, so this issue is no longer valid.  This can be closed.

**Comment by shelane** [comment]
Per comment above and I concur that the error no longer occurs.
