### ISSUE TITLE
Docksal 'bee' command does not work

### ISSUE THREAD

**Issue by Wylbur** [docksal/boilerplate-backdrop#42]
I tested this install profile today, but had issues the install and with running bee commands in Docksal.  

In the bee command file, the root argument uses the docroot path, but we need the absolute path from with the container.  
```fin exec /usr/local/bin/bee/bee.php --root=${DOCROOT_PATH} "$@"```

This command works: 
```fin exec /usr/local/bin/bee/bee.php --root="/var/www/${DOCROOT}" "$@"```

**Comment by shelane** [comment]
In the command, the `$DOCROOT_PATH` is defined as this: `DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"` and the $PROJECT_ROOT is `/var/www` so it is the same as `/var/www/${DOCROOT}".

**Comment by Wylbur** [comment]
Here are steps to reproduce this issue:

1. Clone site to local
2. cd into project folder
3. initialize site `fin init`
4. On the command line, move to the project folder
5. execute `fin bee st`
![2024-08-28_15-25](https://github.com/user-attachments/assets/26353a45-522b-44c3-a1f9-af2210f968b7)

Moving to the docroot yeilds the same result:
![2024-08-28_15-25_1](https://github.com/user-attachments/assets/77bf333c-8222-4f65-8d2d-4c0872a79e5b)

When I execute the following command, we see that bee is installed and working:
`fin exec /usr/local/bin/bee/bee.php st`
